Feat: multi-sample averaging and 50Hz mains filtering
adafruit/Adafruit_CircuitPython_MAX31856 pull request #20
Opened 2022-08-03 09:09 UTC by eirinnm

This PR implements two features from the datasheet:

* On-chip multi-sample averaging (1,2,4,8,16 samples). Default is 1 (no averaging). Using on-chip averaging is much faster than retrieving individual samples and averaging them in user code.
* 50Hz mains frequency notch filter. Default is off (will filter 60Hz instead). #18

2022-08-03 15:05 UTC, ladyada commented
hi please create functions to set/get the freq filter (none, 50, 60?) and oversampling rather than setting once in init :)

2022-08-05 17:48 UTC, eirinnm commented
Thanks for the feedback! I've created functions `set_sampling` and `select_mains_filtering` so that these options can be changed after init. For most users they don't have to be called, because the chip has sane defaults (single sampling and 60Hz filter).

2022-08-05 20:38 UTC, caternuson commented
Code logic looks generally OK. But instead of actual function functions, CP lib style is to use Python property feature:
https://docs.circuitpython.org/en/latest/docs/design_guide.html#getters-setters

Look at the `temperature_thresholds` property in this library for an example.

With that form, the following syntax is how they would get used in user code to set:
```python
thermocouple.averaging = 16
thermocouple.noise_rejection = True
```
and to query (get):
```python
print("Averaging =", thermocouple.averaging)
print("Noise Rejection =", thermocouple.noise_rejection)
```

In the above example code snippets, `averaging` and `noise_rejection` are the suggested property names, similar to `temperature_thresholds`.

2022-08-08 13:44 UTC, eirinnm commented
Yes I see. Thanks for the advice! I've implemented it using property getter/setters now.

2022-08-08 17:30 UTC, dhalbert requested changes
One spelling fix.

2022-08-08 17:30 UTC, dhalbert commented on adafruit_max31856.py
>          """Wait to retreive temperature of the cold junction in degrees Celsius. (read-only)"""
```suggestion
        """Wait to retrieve temperature of the cold junction in degrees Celsius. (read-only)"""
```

2022-08-08 18:05 UTC, caternuson commented
LGTM. Nice job switching to property approach!

Functionally tested, without a TC connected, on Itsy M0:
```python
Adafruit CircuitPython 7.3.2 on 2022-07-20; Adafruit ItsyBitsy M0 Express with samd21g18
>>> import board
>>> import adafruit_max31856
>>> import digitalio
>>> cs = digitalio.DigitalInOut(board.D10)
>>> cs.switch_to_output()
>>> max = adafruit_max31856.MAX31856(board.SPI(), cs)
>>> max.reference_temperature
24.375
>>> max.averaging
1
>>> max.averaging = 16
>>> max.averaging
16
>>> max.averaging = 42
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "adafruit_max31856.py", line 190, in averaging
ValueError: Num_samples must be one of 1,2,4,8,16
>>> max.noise_rejection
60
>>> max.noise_rejection = 50
>>> max.noise_rejection
50
>>> max.noise_rejection = 23
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "adafruit_max31856.py", line 218, in noise_rejection
ValueError: Frequency must be 50 or 60
>>>  
```

2022-08-09 12:50 UTC, eirinnm commented
Thanks all, I've enjoyed contributing to this library.

2022-08-15 15:43 UTC, FoamyGuy approved these changes
Looks good to me, verified the open change requested was completed. 

Thanks for the improvement @eirinnm

2022-08-15 15:43 UTC, merged